file <- file("household_power_consumption.txt")
data <-  read.table(text = grep("^[1,2]/2/2007", readLines(file), value = TRUE), header = TRUE, sep = ";",  col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
png(file = "myplot.1")
hist(x = data$Global_active_power, xlab = "Global Active Power (kilowatts)", col = "red", ylab = "Frequency", main = paste("Global Active Power"))
dev.off()
