file <- file("household_power_consumption.txt")
data <-  read.table(text = grep("^[1,2]/2/2007", readLines(file), value = TRUE), header = TRUE, sep = ";",  col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
png(file = "plot3.png")
plot(x = datetime, y = data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(x = datetime, y = data$Sub_metering_2, type = "l", xlab = "", ylab = "Energy sub metering", col = "red")
points(x = datetime, y = data$Sub_metering_3, type = "l", xlab = "", ylab = "Energy sub metering", col = "blue")
legend(legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, "topright")
dev.off()
